@ECHO OFF
SETLOCAL EnableDelayedExpansion
TITLE INTERNET CHECKER

REM ALMACENANDO ARGUMENTOS
SET PINGS=%1
SET TIME=%2
SET IP=%3

REM VALIDANDO ARGUMENTOS 
IF [!PINGS!] EQU [] (GOTO USAGE)
IF [!TIME!] EQU [] (GOTO USAGE)
IF [!IP!] EQU [] (GOTO USAGE)

GOTO START

REM INICIANDO CON EL PING -> GUARDANDO EL ERRORLEVEL DEL PING -> BUSCANDO PALABRA CLAVE -> GUARDANDO ERRORLEVEL PALABRA CLAVE
:START
SET /A ATTEMPS=!ATTEMPS!+1
ECHO [93m ATTEMPING CONNECTION FOR !ATTEMPS! TIME[0m 
PING -n !PINGS! !IP! > "%tmp%\checkerfile.inf"
SET PINGLEVEL=!ERRORLEVEL!
TYPE %temp%\checkerfile.inf | FIND "Respuesta desde %IP%"
SET FINDLEVEL=!ERRORLEVEL!
DEL %TMP%\checkerfile.inf
IF [!PINGLEVEL!] EQU [0] (SET /A VAR1=1) ELSE (SET /A VAR1=0)
IF [!FINDLEVEL!] EQU [0] (SET /A VAR2=1) ELSE (SET /A VAR2=0)
SET /A SUM=!VAR1!+!VAR2!
IF [!SUM!] EQU [2] (GOTO WEHAVE) ELSE (GOTO DONTHAVE)

:WEHAVE
ECHO 
ECHO [92mRECEIVING RESPONSE FROM %IP%[0m
PING -n 1 !IP!
CHOICE /C OC /N /T !TIME! /D C /M "PRESS THE "O" KEY TO DISMISS THE ALARM (C/o)-->"
IF %ERRORLEVEL% NEQ 1 (GOTO WEHAVE) ELSE (GOTO EOF)

:DONTHAVE
ECHO [31m WE DON'T HAVE INTERNET CONNECTION[0m
TIMEOUT /T %TIME% > NUL
GOTO START

:USAGE
ECHO USAGE:
ECHO        [92michecker	 [0mPINGS TIME IP
ECHO.

ECHO PINGS          THE NUMBER OF ICMP PACKETS THAT WILL BE TRANSMITED 
ECHO                PER ATTEMP IN ORDER TO GET A RESPONSE FROM THE IP
ECHO.
ECHO TIME           THE SECONDS TO DELAY THE ATTEMPS
ECHO.
ECHO IP             THE TARGET WHICH WE WANT TO GET RESPONSE

:EOF 
EXIT /B 0