@ECHO OFF
TITLE STOP PROCESS
:START
SET proc=
SET /P proc="ENTER THE IM OF THE PROCESS-> "
CHOICE /C YN /N /T 6 /D Y /M "ARE YOU SURE THAT %proc% IS THE PROCESS? (Y/n)"
IF %ERRORLEVEL% EQU 2 (GOTO START)

REM SHOWING PROCESS
TASKLIST | FIND /I "%proc%"
IF %ERRORLEVEL% NEQ 0 (GOTO NOTFOUND) ELSE (GOTO FOUND)
TIMEOUT /T 4 >NUL



:NOTFOUND
ECHO [31mTHE PROCESS WASN'T FOUND ^! ^![0m 
TIMEOUT /T 5 >NUL
GOTO EOF

:FOUND
ECHO [92mTHE PROCESS WAS FOUND ^! ^![0m  
CHOICE /C YN /N /T 10 /D Y /M "DO YOU WANT TO STOP THESE PROCECESS? (Y/n) ->"

IF %ERRORLEVEL% EQU 1 (GOTO STOPPROCS) ELSE (GOTO EOF)

:STOPPROCS
TASKKILL /IM %proc%.* /F 
ECHO %ERRORLEVEL% 
TIMEOUT /T 3 >NUL

:EOF
EXIT /B 0